const USER_HASH="cea4c06a97757ebf2ccc3705d90caa041828f3992e2f8572afa0cbdd7f5a2b2f";
const PASS_HASH="86714587a9bc6ab594842760636a8826eef41ad029dbb7e6c6a535e78c4eb4e7";
const STORAGE_KEY="encanto_elixir_products_v1";
const WHATSAPP_URL="https://wa.me/573046835989";
const INSTAGRAM_URL="https://instagram.com/Encanto.Elixir";
let products=[];let adminMode=false;let isLoggedIn=false;const $=id=>document.getElementById(id);

async function sha256(t){const d=new TextEncoder().encode(t);const h=await crypto.subtle.digest("SHA-256",d);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function loadProducts(){const s=localStorage.getItem(STORAGE_KEY);products=s?JSON.parse(s):structuredClone(window.DEFAULT_PRODUCTS);products=products.map(p=>({details:"",category:"Catálogo",image:"",...p}));}
function saveProducts(){localStorage.setItem(STORAGE_KEY,JSON.stringify(products));}
function sortProducts(){products.sort((a,b)=>a.name.localeCompare(b.name,"es",{sensitivity:"base"}));}
function initPublicCatalog(){$("whatsappLink").href=WHATSAPP_URL;$("instagramLink").href=INSTAGRAM_URL;loadProducts();sortProducts();renderCategories();renderCatalog();if(sessionStorage.getItem("encanto_auth")==="ok"){isLoggedIn=true;$("adminToggle").textContent="Panel admin";$("logoutBtn").classList.remove("hidden");}}
initPublicCatalog();
function openLogin(){$("loginView").classList.remove("hidden");$("loginError").textContent="";setTimeout(()=>$("username").focus(),50);}
function closeLogin(){$("loginView").classList.add("hidden");}
$("adminToggle").onclick=()=>{if(!isLoggedIn){openLogin();return;}adminMode=!adminMode;$("adminPanel").classList.toggle("hidden",!adminMode);document.body.classList.toggle("admin-on",adminMode);$("adminToggle").textContent=adminMode?"Ocultar admin":"Panel admin";renderCatalog();};
$("closeLoginBtn").onclick=closeLogin;$("loginView").addEventListener("click",e=>{if(e.target.id==="loginView")closeLogin();});
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();const u=await sha256($("username").value.trim());const p=await sha256($("password").value);if(u===USER_HASH&&p===PASS_HASH){sessionStorage.setItem("encanto_auth","ok");isLoggedIn=true;closeLogin();$("logoutBtn").classList.remove("hidden");adminMode=true;$("adminPanel").classList.remove("hidden");document.body.classList.add("admin-on");$("adminToggle").textContent="Ocultar admin";renderCatalog();}else $("loginError").textContent="Usuario o clave incorrectos.";}); 
$("logoutBtn").onclick=()=>{sessionStorage.removeItem("encanto_auth");isLoggedIn=false;adminMode=false;$("adminPanel").classList.add("hidden");document.body.classList.remove("admin-on");$("adminToggle").textContent="Iniciar sesión";$("logoutBtn").classList.add("hidden");renderCatalog();};
$("searchInput").addEventListener("input",renderCatalog);$("categoryFilter").addEventListener("change",renderCatalog);
function normalizeText(t){return String(t||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
function formatPrice(p){const c=String(p||"").trim();return c.startsWith("$")?c:"$"+c;}
function renderCategories(){const cs=[...new Set(products.map(p=>p.category||"Catálogo"))].sort();$("categoryFilter").innerHTML='<option value="">Todas las categorías</option>'+cs.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");}
function renderCatalog(){const q=normalizeText($("searchInput").value.trim());const cat=$("categoryFilter").value;const f=products.filter(p=>{const h=normalizeText(`${p.name} ${p.price} ${p.category||"Catálogo"} ${p.details||""}`);return(!q||h.includes(q))&&(!cat||(p.category||"Catálogo")===cat);});$("countText").textContent=`${f.length} fragancias disponibles`;$("catalogGrid").innerHTML=f.map(p=>`<article class="card" onclick="openProductModal(${p.id})"><div class="card-actions" onclick="event.stopPropagation()"><button onclick="editProduct(${p.id})">Editar</button><button class="danger" onclick="deleteProduct(${p.id})">Borrar</button></div><div class="image-box">${p.image?`<img src="${p.image}" alt="${escapeHtml(p.name)}">`:`<div class="placeholder">Subir<br>imagen</div>`}</div><div><h3>${escapeHtml(p.name)}</h3><span class="price">${formatPrice(p.price)}</span>${p.details?`<p class="details">${escapeHtml(p.details)}</p>`:""}<div class="category">${escapeHtml(p.category||"Catálogo")}</div></div></article>`).join("");}
$("productForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("productId").value?Number($("productId").value):Date.now();const ex=products.find(p=>p.id===id);const file=$("productImage").files[0];const image=file?await fileToDataURL(file):(ex?.image||"");const product={id,name:$("productName").value.trim(),price:$("productPrice").value.trim().replace("$",""),category:$("productCategory").value.trim()||"Catálogo",details:$("productDetails").value.trim(),image};if(ex)Object.assign(ex,product);else products.unshift(product);sortProducts();saveProducts();renderCategories();renderCatalog();clearForm();});
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$("productId").value=p.id;$("productName").value=p.name;$("productPrice").value=p.price;$("productCategory").value=p.category||"Catálogo";$("productDetails").value=p.details||"";window.scrollTo({top:document.querySelector(".admin-panel").offsetTop-20,behavior:"smooth"});}
function deleteProduct(id){if(confirm("¿Borrar esta loción?")){products=products.filter(p=>p.id!==id);sortProducts();saveProducts();renderCategories();renderCatalog();}}
function clearForm(){$("productForm").reset();$("productId").value="";}$("clearForm").onclick=clearForm;
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(products,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="catalogo-encanto-elixir.json";a.click();URL.revokeObjectURL(a.href);};
$("importInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;products=JSON.parse(await file.text()).map(p=>({details:"",category:"Catálogo",image:"",...p}));sortProducts();saveProducts();renderCategories();renderCatalog();e.target.value="";};
$("resetBtn").onclick=()=>{if(confirm("Esto borra cambios locales y restaura la lista inicial. ¿Continuar?")){localStorage.removeItem(STORAGE_KEY);loadProducts();sortProducts();renderCategories();renderCatalog();}};
function openProductModal(id){const p=products.find(x=>x.id===id);if(!p)return;$("productModalContent").innerHTML=`<div class="modal-product-image">${p.image?`<img src="${p.image}" alt="${escapeHtml(p.name)}">`:`<div class="placeholder">Imagen<br>pendiente</div>`}</div><h2>${escapeHtml(p.name)}</h2><span class="price">${formatPrice(p.price)}</span>${p.details?`<p class="modal-details">${escapeHtml(p.details)}</p>`:""}<a class="buy-btn" target="_blank" rel="noopener" href="${WHATSAPP_URL}?text=${encodeURIComponent("Hola, me interesa la fragancia "+p.name+" del catálogo Encanto Elixir.")}">Comprar por WhatsApp</a>`;$("productModal").classList.remove("hidden");}
$("closeProductModal").onclick=()=>$("productModal").classList.add("hidden");$("productModal").addEventListener("click",e=>{if(e.target.id==="productModal")$("productModal").classList.add("hidden");});
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
